name: todo_sqlite
description: "To Do List com SQLite - Seminario Grupo 5 (Dispositivos Moveis I, Unitins)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8      # icones no estilo iPhone
  sqflite: ^2.4.2              # SQLite no Android, iOS e macOS
  sqflite_common_ffi: ^2.3.0   # SQLite no Windows e no Linux
  path: ^1.9.0                 # monta o caminho do arquivo .db
  sqflite_common_ffi_web: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Imagens usadas no app (logo da Unitins).
  assets:
    - assets/imagens/
